const API_05 = [
    {
        id: 'flush-headingOne',
        dataBsTarget: "#flush-collapseOne",
        ariaControls: "flush-collapseOne",
        id2: "flush-collapseOne",
        ariaLabelledby: "flush-headingOne",
        title: 'What is Netflix?',
        info: "Netflix is a streaming service that offers a wide variety of award-winning TV shows, movies, anime, documentaries and more - on thousands of internet-connected devices.\nYou can watch as much as you want, whenever you want, without a single ad - all for one low monthly price.There's always something new to discover, and new TV shows and movies are added every week!",
    },
    {
        id: 'flush-headingTwo',
        dataBsTarget: "#flush-collapseTwo",
        ariaControls: "flush-collapseTwo",
        id2: "flush-collapseTwo",
        ariaLabelledby: "flush-headingTwo",
        title: 'How much does Netflix cost?',
        info: "Watch Netflix on your smartphone, tablet, Smart TV, laptop, or streaming device, all for one fixed monthly fee. Plans range from ₹ 149 to ₹ 649 a month. No extra costs, no contracts.",
    },
    {
        id: 'flush-headingThree',
        dataBsTarget: "#flush-collapseThree",
        ariaControls: "flush-collapseThree",
        id2: "flush-collapseThree",
        ariaLabelledby: "flush-headingThree",
        title: 'Where can I watch?',
        info: "Watch anywhere, anytime. Sign in with your Netflix account to watch instantly on the web at netflix.com from your personal computer or on any internet-connected device that offers the Netflix app, including smart TVs, smartphones, tablets, streaming media players and game consoles.\nYou can also download your favourite shows with the iOS, Android, or Windows 10 app.Use downloads to watch while you're on the go and without an internet connection. Take Netflix with you anywhere.",
    },
    {
        id: 'flush-headingFour',
        dataBsTarget: "#flush-collapseFour",
        ariaControls: "flush-collapseFour",
        id2: "flush-collapseFour",
        ariaLabelledby: "flush-headingFour",
        title: 'How do I cancle?',
        info: "Netflix is flexible. There are no annoying contracts and no commitments. You can easily cancel your account online in two clicks. There are no cancellation fees - start or stop your account anytime.",
    },
    {
        id: 'flush-headingFive',
        dataBsTarget: "#flush-collapseFive",
        ariaControls: "flush-collapseFive",
        id2: "flush-collapseFive",
        ariaLabelledby: "flush-headingFive",
        title: 'What can I watch on Netflix?',
        info: "Netflix has an extensive library of feature films, documentaries, TV shows, anime, award-winning Netflix originals, and more. Watch as much as you want, anytime you want.",
    },
    {
        id: 'flush-headingSix',
        dataBsTarget: "#flush-collapseSix",
        ariaControls: "flush-collapseSix",
        id2: "flush-collapseSix",
        ariaLabelledby: "flush-headingSix",
        title: 'Is Netflix good for kids?',
        info: "The Netflix Kids experience is included in your membership to give parents control while kids enjoy family-friendly TV shows and films in their own space.\nKids profiles come with PIN - protected parental controls that let you restrict the maturity rating of content kids can watch and block specific titles you don't want kids to see.",
    },
]

export default API_05;